version: '3.9'
services:
  # service 1
  server:
    image: 'mesh_server_image:v0.1'
    build: 
      context: .
      target: mesh_server_image
    container_name: 'server'
    ports:
      - 5000:5000
      - 9200:9200
    restart: unless-stopped
    volumes:
      - ./server:/opt/server
    command: >
      /bin/sh -c 'cd /opt/server; if [ ! -d "/opt/server/Model" ]; then mv /opt/Model . ; fi; python3 main.py;'
    # command: >
    #   /bin/sh -c 'tail -f /dev/null'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  
  # service 2
  client:
    image: 'mesh_client_image:v0.1'
    build: 
      context: .
      target: mesh_client_image
    container_name: 'client'
    ports:
      - 80:3000
      - 1984:1984
    restart: unless-stopped
    volumes:
      - ./client:/opt/client
    command: >
      /bin/sh -c 'cd /opt/client/web-app; if [ ! -d "/opt/server/node_modules" ]; then npm install; fi; npm start'
    # command: >
    #    /bin/sh -c 'tail -f /dev/null'