version: '3.9'
services:
  # service 1
  server:
    image: 'mesh_image:v1.0'
    build: .
    container_name: 'server'
    ports:
      - 5000:5000
      - 9200:9200
    restart: unless-stopped
    volumes:
      - ./server:/opt/server
    command: >
      /bin/sh -c 'cd /opt/server; if [ ! -d "/opt/server/Model" ]; then mv /opt/Model . ; fi; python3 main.py;'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  # service 2
  client:
    image: 'mesh_image:v1.0'
    container_name: 'client'
    ports:
      - 3000:3000
      - 1984:1984
    restart: unless-stopped
    # volumes:
    #   - ./client:/opt/client
    # command: >
    #   /bin/sh -c 'cd /opt/client/web-app && npm start'
    command: >
       /bin/sh -c 'tail -f /dev/null'